[package]
name = "opnsense-unbound-webhook"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json", "serde_json"] }
# rocket_contrib = "0.4.11"
serde = { version = "1.0.219", features = ["derive"] }
